### ISSUE TITLE
Question regarding the details of training DreamLLM

### ISSUE THREAD

**Issue by williamium3000** [RunpeiDong/DreamLLM#12]
Hi Runpei,
Thanks for open-sourcing such nice work!
I am wondering how you managed to parallel generative pertaining to train DreamLLM on interleaved image texts data?
Given that you need to input 64 queries then how do you handle image input?
Assume the following,
text-text-text-text-image-text-text-text-image
text are just tokens, if you replace image to be   **<dream> query query ... <\dream>**:
text-text-text-text-**<dream> query query ... <\dream>**-text-text-text-**<dream> query query ... <\dream>**
Then during training the text-text-text tokens in the middle are actually conditioning on <dream> query query ... <\dream> tokens instead of real images.
However, during inference, images will be generated by SD and input to the model to sequentially decode the rest tokens.
Would not there be a mismatch during training and inferencing?

Can you elaborate more on the training details? i.e. how exactly do you format your training data to do parallel generative pertaining?

Thank you so much for your effort and time!!

Best
Yijiang

**Comment by RunpeiDong** [comment]
Hi @williamium3000,

Thank you for your interest in our work. It is indeed a good question, and we have actually discussed this question before implementation. 
- Yes, indeed. During training, we are using real images instead of the generated images. This is because parallel training will be very difficult if we use the generated images. It will also be very, very slow since every subsequent content generation will depend on the generated image. Consider a sample with 3 images, then we must wait for every image to be generated, which results in 3 times inference, which is very time-consuming. Besides, different image numbers will make it difficult to encode at batch level. **This is definitely a disaster when scaling up training data. That's why we have to do this parallel training using real images, only one-time batch-level inference is required.**
- During inference, every image is generated and then input to the network for the following content generation. Yes, there is a domain gap. However, the gap won't be very large. There are several reasons. First of all, if you take a look at real interleaved data, such as MMC4. You will find that the data is far from satisfactory. For example, many data have images that are not actually related to the description. In some cases, the images are all almost the same (e.g., an article discussing an industrial production thing, and the images may all be the product instead of the history, technology, cost, etc.). In contrast, the generated images are typically more related to the previous context due to the strong text-to-image training. Secondly, the generated image quality is also good enough. You may find the same problem with MMC4 having a lot of low-quality images. However, the generated images are typically good, and they will be better if you use the proper CFG and negative prompts.
- Regarding the training detail. Please check out what I have described before. For more information, it is always better to take a close look at the codes. I have provided the interleaved dataset class and all training details in the code.

I hope this could help you.

**Comment by williamium3000** [comment]
Thank you so much for your prompt answer!!
If you use real images during training, **then how do you train the learnable query token**?
I think my confusion lies in whether you use query tokens or real image features as input to the LLM during the training. 
If you use query token, then during training the tokens that comes after will condition on query tokens instead of images, which I think does not make sense, because if basically means there are no image input?
Also this is a gap between training and inference (as you generate images then input the generated image to generate subsequent tokens)
But on the other hand, **if you use real images feature as input, then how do learn your query tokens (if it's not involved in the training process)** 
Or there there a third training process that learns the query separately?

I will definitely check the code, but thank you so much for your effort and time anyway!!
Best
Yijiang

**Comment by RunpeiDong** [comment]
Hi @williamium3000,

Yes, of course, we use the dream queries during training. One basic principle is that GPTs use causal attention. So, we first encode the images and texts into hidden states without dream queries. Afterward, a language modeling loss can be applied. Since the interleaved layout is tagged with special tokens, we know where to insert the dream queries for image generation, right? As a result, we use the encoded token sequence and replace the special tokens that indicate dream query positions with real dream queries. Then, the images are generated based on the history semantics. So, you can now apply the diffusion loss (visual modeling loss). All the processes are causal, so every image is generated only based on history texts and images. 

Again, please check the code carefully. You will see that `lm_loss` and `vm_loss` are obtained separately, but the theory behind them is the same, thanks to the causal nature of the GPT-style attention.
The forward process for language modeling is:
https://github.com/RunpeiDong/DreamLLM/blob/fb5f3e06581640cd2123cd50e13fd83f2f7de079/omni/models/dreamllm/modeling_dreamllm.py#L1378

Diffusion training starts from `Let's train diffusion!`, and the forward process for diffusion training is:
https://github.com/RunpeiDong/DreamLLM/blob/fb5f3e06581640cd2123cd50e13fd83f2f7de079/omni/models/dreamllm/modeling_dreamllm.py#L1441
The replacement process where we apply **dream queries** is:
https://github.com/RunpeiDong/DreamLLM/blob/fb5f3e06581640cd2123cd50e13fd83f2f7de079/omni/models/dreamllm/modeling_dreamllm.py#L1414
and:
https://github.com/RunpeiDong/DreamLLM/blob/fb5f3e06581640cd2123cd50e13fd83f2f7de079/omni/models/dreamllm/modeling_dreamllm.py#L1083

**Comment by williamium3000** [comment]
Will definitely check the code!!
Thank you so much !!!

**Comment by RunpeiDong** [comment]
Excellent. You are welcome!

**Comment by RunpeiDong** [comment]
Hi @williamium3000,

Is my answer helpful? Do you need further help?

**Comment by williamium3000** [comment]
Yes, that's really helpful!! thank you so much !!
