### ISSUE TITLE
Pre-trained weights for SDXL version

### ISSUE THREAD

**Issue by ktrk115** [RunpeiDong/DreamLLM#18]
Thank you for sharing your codebase. The omni library looks really great!
I would like to use DreamLLM with SDXL. Will the pre-trained weights be released on HuggingFace?

**Comment by RunpeiDong** [comment]
Hi @ktrk115,

Thank you for your interest! I currently have no resources to do it. However, I have provided the implementation and training scripts for DreamLLM-SDXL. You can train a DreamLLM-SDXL easily with the provided script. Please note the tips I wrote before you train the model.

Best,
Runpei

**Comment by ktrk115** [comment]
Hi Runpei, thanks for your reply! Your training tips will definitely help. I would like to train it by myself but am concerned about the GPU requirements. Do you have an estimate of how long it would take to train DreamLLM-SDXL with mid-scale GPU resources, say 8 A100 80GB GPUs available?

**Comment by RunpeiDong** [comment]
Hi @ktrk115,

To get a result quickly, I suggest you run stage-I on LAION-400m using approximately 20M images. You should get a reasonable result before the training is finished. For example, you can try to test the model every 500 or 1k steps. If you train the model on an 8xA100 machine, the training should not be very time-consuming. But note that since SDXL requires a larger resolution and the batch size would be smaller, making the training a bit slower.

**Comment by ktrk115** [comment]
Thank you for your kind advice! I'll try that once I'm familiar with the omni library.

**Comment by RunpeiDong** [comment]
You are welcome.

**Comment by RunpeiDong** [comment]
Hi @ktrk115,

We recently trained a new T2I and personalization DreamLLM-SDXL model for another benchmark project. I will publish this model, and I will ping you then.

**Comment by ktrk115** [comment]
Sounds great, looking forward to it!
