### ISSUE TITLE
Clarification Regarding Visual embeddings

### ISSUE THREAD

**Issue by Shaurya026** [RunpeiDong/DreamLLM#4]
Hi, thanks for this new techniques for extending MLLMs for interleaved documents. 

I had a doubt regarding visual encoder in fig-2 and section 3. 

<img width="1174" alt="Screenshot 2023-10-02 at 7 20 48 PM" src="https://github.com/RunpeiDong/DreamLLM/assets/43774789/a4f7c609-3d40-401d-90e7-dc09431827ab">

In figure 2, as I understand that "during training" itself the model is learning to generate `<dream>` tokens as the cat example is given for which `dream queries` are learned which are essentially textual inversion embeddings that can be synergised with the remaining context of the textual tokens. (it shows inference stream, but interleaved doc shows text with cat image so it confuses me a bit)
but as that happens, are we again sending the input image to the models via CLIP encodings via an extra projection encodings as shown in the diagram. (is that right? or we're just using the dream queries further ahead)

Also, for taking visual inputs are we following a similar pipeline of CLIP embeddings with projection like that of EMU?  

Thank you

**Comment by RunpeiDong** [comment]
Hi @Shaurya026,

Thanks for your question.
- Yes. All generated images are sent back to the model for the following token prediction. This is important since only when it is fed back, the real interleaved distribution is modeled.
- The visual input encoding is similar to Emu. This practice was first introduced by Kosmos-1 (as far as I know), where only a linear projection layer is used as the visual connector, followed by many works, including Emu. However, the visual encoder may be different such as CLIP-G or CLIP-L. Btw, some other works use more complicated architectures, such as a Q-former or Perceiver architecture as the visual connector (projection).

**Comment by Shaurya026** [comment]
Thanks, that helps! 👍🏻
