### ISSUE TITLE
How does shard_list.json looks like.

### ISSUE THREAD

**Issue by zheedong** [RunpeiDong/DreamLLM#6]
Hello, thank you for your great work.

I wonder how does shard_list.json looks like for training.
Can you give me any sample?

Thank you.

**Comment by RunpeiDong** [comment]
Hi @zheedong,

Thank you for your question. The `shard_list.json` is the metafile that saves the exact path of `tar` files. It is because these web datasets are too large that they are typically stored on the cloud instead of on the local disk. 

For example, a `shard_list.json` may look like this:

```
[
"s3://Laion400M/laion400m_part0/07063.tar",
"s3://Laion400M/laion400m_part0/08071.tar",
]
```

For more information about `webdataset`, please see [here](https://github.com/webdataset/webdataset).

**Comment by FolSpark** [comment]
how to prepare shard_list.json from the original file downloaded from huggingface,such as [laion400m](https://huggingface.co/datasets/laion/laion400m/tree/main)?
Can you provide a script?

thanks

**Comment by RunpeiDong** [comment]
It depends on where you store the tar files. You just record all the tar file locations of laion400m on your machine, save it as a list, and then you are good.

**Comment by FolSpark** [comment]
I don't know how to prepare tar files. I searched for these:
https://github.com/rom1504/img2dataset/blob/main/dataset_examples/laion400m.md
https://github.com/rom1504/img2dataset/blob/main/dataset_examples/mscoco.md

Are tar files made from these scripts？

**Comment by RunpeiDong** [comment]
Yes. Follow the [instructions](https://github.com/rom1504/img2dataset/blob/main/README.md) carefully and remember to download tar files for `webdataset` usage.

**Comment by FolSpark** [comment]
Ok, I understand. Thank you very much!
