### ISSUE TITLE
vm_loss config

### ISSUE THREAD

**Issue by zheedong** [RunpeiDong/DreamLLM#7]
Hi, can you let me know what is correct training config in stage 1 vm_loss?

Is it in StableDiffusionHead,
* drop_prob = 0.1
* noise_offset = 0.0
* input_perturbation = 0.1
* snr_gamma = 5.0
right?

Where can I see proper training config?

Thank you.

**Comment by RunpeiDong** [comment]
Hi @zheedong,

No. The recommendation is from the Hugginface team instead of us. We use the default configurations as follows:
- drop_prob = None
- noise_offset = 0.0
- input_perturbation = 0.0
- snr_gamma = None

The configuration can be modified, but we have not. So, the configuration is just the default.

**Comment by RunpeiDong** [comment]
Hi @zheedong,

Is it clear now or you need some more help?

**Comment by zheedong** [comment]
Ah sorry for late.

No thank yo for your help.
